# Generated by Django 5.2.2 on 2025-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='berita/'),
        ),
    ]
